export enum TextFormFieldType {
    INPUT = "INPUT",
    SELECT_GROUP = "SELECT_GROUP",
    SELECT = "SELECT",
    SELECT_CREATABLE = "SELECT_CREATABLE",
    SELECT_ASYNC = "ASYNC_SELECT",
    SELECT_ASYNC_CREATABLE = "ASYNC_SELECT_CREATABLE",
    IMAGE = "IMAGE",
    DATE_PICKER = "DATE_PICKER",
    CHECKBOX = "CHECKBOX"
}